### ISSUE TITLE
Needs more Raft

### ISSUE THREAD

**Issue by pirate** [pirate/mesh-networking#12]
Raft is a beautiful hammer, lets find some more nails to hit with it!

**Comment by glerinsonum** [comment]
@pirate Brother, how i can use thing product, because i do no know how configure json web server. make one video.

**Comment by pirate** [comment]
There are a bunch of examples in the `examples/` folder, check those to get an idea of how to use this library.  Or do you mean raft? check this out: http://thesecretlivesofdata.com/raft/
