### ISSUE TITLE
fmt() function in multinode.py

### ISSUE THREAD

**Issue by zlgunn** [pirate/mesh-networking#5]
```python
def fmt(type, value, fallback=None):
    try:
        return type(value)
    except Exception:
        return fallback
```
When called here ```num_nodes = fmt(int, input("How many nodes do you want? (26):"), 26)``` I get "Unexpected EOF when parsing" error. I found that changing ```input()``` to ```raw_input()``` fixes this in lines 54,55,56 of multinode.py.
Update: changed all instances of ```input()``` to ```raw_input()``` as the former seems to cause issues.

**Comment by pirate** [comment]
This is a Python 3 vs Python 2 change http://stackoverflow.com/questions/10885537/raw-input-has-been-eliminated-from-python-3-2
